name: Hardhart tests

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      # disposable private key, meant as placeholder.
      # do not use in production
      MAINNET_PRIVATE_KEY: "0x8b6734a335e529e584f2b1b77f7a07cdd1e46991a5b2cd0cef9c933a8710a1c2"
      TESTNET_PRIVATE_KEY: "0x8b6734a335e529e584f2b1b77f7a07cdd1e46991a5b2cd0cef9c933a8710a1c2"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - run: yarn install
      - run: pip install slither-analyzer
      - run: yarn run hardhat compile
      - run: yarn run hardhat test
